version: '3.2'
services:
  web:
    container_name: react
    image: bayesimpact/react-base:latest
    volumes:
      - app-sync:/usr/app/src:nocopy


#    environment:
#      - WEB_DOCUMENT_ROOT=/var/www/grav
#      - WEB_DOCUMENT_INDEX=index.php
#      - php.display_errors=On

#    working_dir: /usr/app

    ports:
      - 8080:80

    networks:
      mynetwork:
        aliases:
          - dev.cookcloud.de


volumes:
  app-sync:
    external: true

networks:
  mynetwork:
    driver: bridge
